/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface5;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

/**
 *
 * @author Vinicios
 */
public class Notepad extends javax.swing.JFrame {

    /**
     * Creates new form Notepad
     */
    public Notepad() {
        initComponents();
    }

    public JTextArea getAreaDeTexto() {
        return areaDeTexto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDeTexto = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        novoArquivo = new javax.swing.JMenuItem();
        abrirArquivo = new javax.swing.JMenuItem();
        salvarArquivo = new javax.swing.JMenuItem();
        fecharArquivo = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        localizar = new javax.swing.JMenuItem();
        substituir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        fonte = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        barraDeFerramentas = new javax.swing.JMenuItem();
        barraDeStatus = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        exibirAjuda = new javax.swing.JMenuItem();
        sobreOBlocoDeNotas = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaDeTexto.setColumns(20);
        areaDeTexto.setRows(5);
        jScrollPane1.setViewportView(areaDeTexto);

        jMenu1.setText("Arquivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        novoArquivo.setText("Novo Arquivo");
        jMenu1.add(novoArquivo);

        abrirArquivo.setText("Abrir Arquivo");
        abrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArquivoActionPerformed(evt);
            }
        });
        jMenu1.add(abrirArquivo);

        salvarArquivo.setText("Salvar Arquivo");
        salvarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarArquivoActionPerformed(evt);
            }
        });
        jMenu1.add(salvarArquivo);

        fecharArquivo.setText("Fechar Arquivo");
        jMenu1.add(fecharArquivo);

        sair.setText("Sair");
        jMenu1.add(sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        localizar.setText("Localizar");
        jMenu2.add(localizar);

        substituir.setText("Substituir");
        jMenu2.add(substituir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Formatar");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        fonte.setText("Fonte");
        fonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fonteActionPerformed(evt);
            }
        });
        jMenu3.add(fonte);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Exibir");

        barraDeFerramentas.setText("Barra de Ferramentas");
        jMenu4.add(barraDeFerramentas);

        barraDeStatus.setText("Barra de Status");
        jMenu4.add(barraDeStatus);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ajuda");

        exibirAjuda.setText("Exibir Ajuda");
        jMenu5.add(exibirAjuda);

        sobreOBlocoDeNotas.setText("Sobre o Bloco de Notas");
        jMenu5.add(sobreOBlocoDeNotas);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArquivoActionPerformed
        JFileChooser abrir = new JFileChooser();
        int opcao = abrir.showOpenDialog(this);
        if(opcao == JFileChooser.APPROVE_OPTION){
            areaDeTexto.setText("");
            try {
                Scanner scan = new Scanner(new FileReader(abrir.getSelectedFile().getPath()));
                while(scan.hasNext()){
                    areaDeTexto.append(scan.nextLine() + "\n");
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_abrirArquivoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void salvarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarArquivoActionPerformed
        JFileChooser salvar = new JFileChooser();
        int opcao = salvar.showSaveDialog(this);
        
        try {
            FileWriter arquivo = new FileWriter(salvar.getSelectedFile());
            BufferedWriter saida = new BufferedWriter(arquivo);
            saida.write(areaDeTexto.getText());
            saida.close();
        } catch (IOException ex) {
            Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_salvarArquivoActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void fonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fonteActionPerformed
        FormatarFonte fonte = new FormatarFonte(this, false);
        fonte.setVisible(true);
        
    }//GEN-LAST:event_fonteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirArquivo;
    private javax.swing.JTextArea areaDeTexto;
    private javax.swing.JMenuItem barraDeFerramentas;
    private javax.swing.JMenuItem barraDeStatus;
    private javax.swing.JMenuItem exibirAjuda;
    private javax.swing.JMenuItem fecharArquivo;
    private javax.swing.JMenuItem fonte;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem localizar;
    private javax.swing.JMenuItem novoArquivo;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem salvarArquivo;
    private javax.swing.JMenuItem sobreOBlocoDeNotas;
    private javax.swing.JMenuItem substituir;
    // End of variables declaration//GEN-END:variables
}
